namespace DiscogsApiClient.SourceGenerator.ApiClientSourceGenerator.Models.MethodParameters;

internal sealed record QueryParameter(Shared.Models.ParsedParameterTypeInfo TypeInfo, QueryParameterType ParameterType);
