<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAotCompatible>true</IsAotCompatible>
		<AnalysisMode>All</AnalysisMode>
		<LangVersion>latest</LangVersion>
		<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
		<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
	</PropertyGroup>

	<PropertyGroup>
		<Title>DiscogsApiClient</Title>
		<Authors>Alexander Jurk</Authors>
		<Description>This is a library for authenticated access to the Discogs database.</Description>
		<PackageProjectUrl>https://github.com/damidhagor/DiscogsApiClient</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/damidhagor/DiscogsApiClient</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>discogs</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<AssemblyVersion>4.1.1</AssemblyVersion>
		<FileVersion>4.1.1</FileVersion>
		<PackageVersion>4.1.1</PackageVersion>
		<PackageReleaseNotes>Fixed improper parsing of the ``instance_id`` property of collection folder releases.</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DiscogsApiClient.SourceGenerator\DiscogsApiClient.SourceGenerator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="DiscogsApiClient.Tests" />
	</ItemGroup>
</Project>
