namespace DiscogsApiClient;

// General
[JsonSerializable(typeof(ErrorMessage))]
[JsonSerializable(typeof(Image))]
[JsonSerializable(typeof(Pagination))]
// User
[JsonSerializable(typeof(UserProfileUpdateRequest))]
[JsonSerializable(typeof(Identity))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(UserListReleaseInformation))]
// Collection
[JsonSerializable(typeof(CollectionField))]
[JsonSerializable(typeof(CollectionFieldsResponse))]
[JsonSerializable(typeof(CollectionFieldType))]
[JsonSerializable(typeof(CollectionFolder))]
[JsonSerializable(typeof(CollectionFolderCreateRequest))]
[JsonSerializable(typeof(CollectionFolderUpdateRequest))]
[JsonSerializable(typeof(CollectionFolderRelease))]
[JsonSerializable(typeof(CollectionFolderReleaseUpdateRequest))]
[JsonSerializable(typeof(CollectionFolderReleaseNote))]
[JsonSerializable(typeof(CollectionFieldValueUpdateRequest))]
[JsonSerializable(typeof(CollectionFolderReleasesResponse))]
[JsonSerializable(typeof(CollectionFoldersResponse))]
[JsonSerializable(typeof(CollectionValue))]
// Wantlist
[JsonSerializable(typeof(WantlistRelease))]
[JsonSerializable(typeof(WantlistReleasesResponse))]
// Submissions
[JsonSerializable(typeof(Submissions))]
[JsonSerializable(typeof(SubmissionsResponse))]
[JsonSerializable(typeof(SubmissionArtist))]
[JsonSerializable(typeof(SubmissionLabel))]
[JsonSerializable(typeof(SubmissionRelease))]
[JsonSerializable(typeof(SubmissionReleaseArtist))]
[JsonSerializable(typeof(SubmissionReleaseLabel))]
// Contributions
[JsonSerializable(typeof(ContributionsResponse))]
[JsonSerializable(typeof(ContributionRelease))]
[JsonSerializable(typeof(ContributionReleaseArtist))]
[JsonSerializable(typeof(ContributionReleaseLabel))]
// Lists
[JsonSerializable(typeof(ListUser))]
[JsonSerializable(typeof(UserList))]
[JsonSerializable(typeof(UserListsResponse))]
[JsonSerializable(typeof(ListDetails))]
[JsonSerializable(typeof(ListItem))]
[JsonSerializable(typeof(ListItemType))]
[JsonSerializable(typeof(ListItemStats))]
[JsonSerializable(typeof(ListItemStatsEntry))]
// Artist
[JsonSerializable(typeof(Artist))]
[JsonSerializable(typeof(ArtistMember))]
[JsonSerializable(typeof(ArtistRelease))]
[JsonSerializable(typeof(ArtistReleasesResponse))]
// Label
[JsonSerializable(typeof(Label))]
[JsonSerializable(typeof(LabelRelease))]
[JsonSerializable(typeof(LabelReleasesResponse))]
[JsonSerializable(typeof(LabelShortInfo))]
// Release
[JsonSerializable(typeof(MasterRelease))]
[JsonSerializable(typeof(MasterReleaseVersion))]
[JsonSerializable(typeof(MasterReleaseVersionAppliedFilter))]
[JsonSerializable(typeof(MasterReleaseVersionFilter))]
[JsonSerializable(typeof(MasterReleaseVersionFilterFacet))]
[JsonSerializable(typeof(MasterReleaseVersionFilterFacetValue))]
[JsonSerializable(typeof(MasterReleaseVersionFilters))]
[JsonSerializable(typeof(MasterReleaseVersionsResponse))]
[JsonSerializable(typeof(Release))]
[JsonSerializable(typeof(ReleaseArtist))]
[JsonSerializable(typeof(ReleaseCommunity))]
[JsonSerializable(typeof(ReleaseCommunityRating))]
[JsonSerializable(typeof(ReleaseCommunityRatingResponse))]
[JsonSerializable(typeof(ReleaseFormat))]
[JsonSerializable(typeof(ReleaseIdentifier))]
[JsonSerializable(typeof(ReleaseLabel))]
[JsonSerializable(typeof(ReleaseRatingResponse))]
[JsonSerializable(typeof(ReleaseRatingUpdateRequest))]
[JsonSerializable(typeof(ReleaseStats))]
[JsonSerializable(typeof(ReleaseStatsResponse))]
[JsonSerializable(typeof(ReleaseStatValues))]
[JsonSerializable(typeof(TracklistItem))]
[JsonSerializable(typeof(Video))]
// Search
[JsonSerializable(typeof(SearchResult))]
[JsonSerializable(typeof(SearchResultCommunityStats))]
[JsonSerializable(typeof(SearchResultsResponse))]
[JsonSerializable(typeof(SearchResultType))]
[JsonSerializable(typeof(SearchResultUserData))]
// Marketplace
[JsonSerializable(typeof(MarketplaceCurrency))]
[JsonSerializable(typeof(MarketplaceInventoryResponse))]
[JsonSerializable(typeof(MarketplaceListing))]
[JsonSerializable(typeof(MarketplaceListingCondition))]
[JsonSerializable(typeof(MarketplaceListingCreateRequest))]
[JsonSerializable(typeof(MarketplaceListingCreateResponse))]
[JsonSerializable(typeof(MarketplaceListingRelease))]
[JsonSerializable(typeof(MarketplaceListingSleeveCondition))]
[JsonSerializable(typeof(MarketplaceListingStatus))]
[JsonSerializable(typeof(MarketplaceListingUpdateRequest))]
[JsonSerializable(typeof(MarketplaceOriginalPrice))]
[JsonSerializable(typeof(MarketplacePrice))]
[JsonSerializable(typeof(MarketplaceReleaseStats))]
[JsonSerializable(typeof(MarketplaceSeller))]
[JsonSerializable(typeof(MarketplaceSellerStats))]
internal partial class DiscogsJsonSerializerContext : JsonSerializerContext;
