namespace DiscogsApiClient.SourceGenerator;

internal static class Constants
{
    public const string SharedNamespace = "DiscogsApiClient.SourceGenerator.Shared";
    public const string ApiClientNamespace = "DiscogsApiClient.SourceGenerator.ApiClient";
    public const string JsonSerializationNamespace = "DiscogsApiClient.SourceGenerator.JsonSerialization";

    public const string ToolName = "DiscogsApiClient.SourceGenerator";
    public const string ToolVersion = "1.0.0";

    public const string GeneratedFileHeader = "// <auto-generated/>";

    public const string GeneratedCodeAttribute = $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{ToolName}", "{ToolVersion}")]""";
}
